'use client';
import {useEffect,useMemo,useRef,useState} from 'react';
import {DOCTOR_FILTERS,doctorDirectory,emptyDoctorFilters} from '../lib/doctor-directory.js';
const key='medmetric-doctor-directory-v1';
const validFilters=value=>value&&DOCTOR_FILTERS.every(([field])=>Array.isArray(value[field])&&value[field].every(v=>typeof v==='string'));
export default function DoctorDirectory({data,doctorId,onSelect,onAdd,resetVersion=0}){
  const [search,setSearch]=useState(''),[filters,setFilters]=useState(emptyDoctorFilters),[sort,setSort]=useState('name'),[presets,setPresets]=useState([]),[presetName,setPresetName]=useState(''),[ready,setReady]=useState(false),[message,setMessage]=useState('');
  const lastReset=useRef(resetVersion);
  useEffect(()=>{try{const saved=JSON.parse(localStorage.getItem(key)||'null');if(saved){if(validFilters(saved.filters))setFilters(saved.filters);if(typeof saved.search==='string')setSearch(saved.search);if(['name','potential','prescriber'].includes(saved.sort))setSort(saved.sort);if(Array.isArray(saved.presets))setPresets(saved.presets.filter(p=>typeof p.id==='string'&&typeof p.name==='string'&&validFilters(p.filters)));}}catch{}setReady(true);},[]);
  useEffect(()=>{if(ready)try{localStorage.setItem(key,JSON.stringify({filters,search,sort,presets}));}catch{}},[ready,filters,search,sort,presets]);
  useEffect(()=>{if(lastReset.current!==resetVersion){lastReset.current=resetVersion;setFilters(emptyDoctorFilters());setSearch('');}},[resetVersion]);
  const result=useMemo(()=>doctorDirectory(data,{search,filters,sort}),[data,search,filters,sort]);
  const count=Object.values(filters).reduce((total,values)=>total+values.length,0);
  function toggle(field,value){setFilters(current=>({...current,[field]:current[field].includes(value)?current[field].filter(v=>v!==value):[...current[field],value]}));}
  return <aside className="panel doctor-directory"><div className="panel-header"><h2>Doctors</h2><button className="button" onClick={onAdd}>+ Add doctor</button></div><label>Search doctors<input type="search" placeholder="Name, specialty, pharmacy or product" value={search} onChange={e=>setSearch(e.target.value)}/></label>
    <div className="directory-toolbar"><details className="directory-filters"><summary>Filters{count?' · '+count:''}</summary><p className="scope-note">Select multiple values. Counts reflect the other filters and your search.</p>{result.groups.map(group=><details key={group.field}><summary>{group.label}{filters[group.field].length?' · '+filters[group.field].length:''}</summary><div className="directory-options">{group.items.map(item=><label key={item.value}><input type="checkbox" checked={filters[group.field].includes(item.value)} onChange={()=>toggle(group.field,item.value)}/><span>{item.label}</span><small>{item.count}</small></label>)}{!group.items.length&&<small>No values recorded.</small>}</div></details>)}</details><label>Sort<select value={sort} onChange={e=>setSort(e.target.value)}><option value="name">Name</option><option value="potential">Potential</option><option value="prescriber">Prescribers first</option></select></label><button className="text-button" onClick={()=>{setSearch('');setFilters(emptyDoctorFilters());}}>Clear filters</button></div>
    {!!count&&<div className="directory-chips">{result.groups.flatMap(group=>filters[group.field].map(value=><button className="text-button" key={group.field+value} onClick={()=>toggle(group.field,value)}>{group.label}: {group.items.find(item=>item.value===value)?.label||value} ×</button>))}</div>}
    <details className="directory-presets"><summary>Saved filters{presets.length?' · '+presets.length:''}</summary>{presets.map(p=><div className="directory-preset" key={p.id}><button className="text-button" onClick={()=>{setFilters(p.filters);setSearch(p.search||'');setSort(p.sort||'name');}}>{p.name}</button><button className="text-button" aria-label={'Delete saved filter '+p.name} onClick={()=>setPresets(current=>current.filter(item=>item.id!==p.id))}>×</button></div>)}<label>Name this selection<input value={presetName} maxLength={80} onChange={e=>setPresetName(e.target.value)} placeholder="For example: Camp A prescribers"/></label><button className="button" disabled={!presetName.trim()} onClick={()=>{const name=presetName.trim();setPresets(current=>[...current.filter(p=>p.name!==name),{id:crypto.randomUUID(),name,filters,search,sort}]);setPresetName('');setMessage('Filter saved on this device.');}}>Save filter</button><p className="scope-note">Saved filters stay on this device.</p></details>
    {message&&<p role="status" className="scope-note">{message}</p>}<div className="directory-metrics"><strong>{result.metrics.total} doctors</strong><span>{result.metrics.rx} Rx · {result.metrics.nrx} NRx</span><span>{result.metrics.hospitals} hospitals · {result.metrics.pharmacies} pharmacies</span></div>
    {doctorId&&!result.doctors.some(d=>d.Doctor_ID===doctorId)&&<p className="scope-note">The open doctor is outside these filters.</p>}
    <div className="field-doctor-list">{result.doctors.map(d=><button className={d.Prescriber_Status==='Rx'?'doctor-rx':''} key={d.Doctor_ID} type="button" aria-pressed={doctorId===d.Doctor_ID} onClick={()=>onSelect(d.Doctor_ID)}><strong>{d.Doctor_Name}<span className="doctor-status">{d.Prescriber_Status||'Unclassified'}</span></strong><span>{d.Specialties} · {d.Camp}</span><small>{d.Hospital||'Hospital not supplied'} · {data.PHARMACIES.find(p=>p.Pharmacy_ID===d.Pharmacy_ID)?.Pharmacy_Name||'Pharmacy not supplied'}</small><small>Potential {d.Potential||'unknown'}{d.Active==='NO'?' · Inactive':''}</small>{!!result.productNames.get(d.Doctor_ID)?.length&&<small className="doctor-products">{result.productNames.get(d.Doctor_ID).join(', ')}</small>}</button>)}</div>{!result.doctors.length&&<p>No doctors match. Clear filters or change the search.</p>}
  </aside>;
}
