'use client';
import {useEffect,useMemo,useRef,useState} from 'react';
import {DOCTOR_FILTERS,doctorDirectory,emptyDoctorFilters} from '../lib/doctor-directory.js';
const key='medmetric-doctor-directory-v1';
const validFilters=value=>value&&DOCTOR_FILTERS.every(([field])=>Array.isArray(value[field])&&value[field].every(v=>typeof v==='string'));
export function doctorInitials(name){return String(name||'Doctor').replace(/^dr\.?\s+/i,'').trim().split(/\s+/).slice(0,2).map(v=>v[0]).join('').toUpperCase();}
function Icon({kind}){return <svg viewBox="0 0 24 24" aria-hidden="true">{kind==='search'?<><circle cx="10.5" cy="10.5" r="6.5"/><path d="m16 16 5 5"/></>:kind==='filter'?<><path d="M4 7h16M4 17h16"/><circle cx="8" cy="7" r="2"/><circle cx="16" cy="17" r="2"/></>:kind==='bookmark'?<path d="M6 3h12v18l-6-4-6 4Z"/>:kind==='plus'?<path d="M12 5v14M5 12h14"/>:<path d="M5 12h14m-6-6 6 6-6 6"/>}</svg>;}
export default function DoctorDirectory({data,doctorId,onSelect,onAdd,resetVersion=0}){
  const [search,setSearch]=useState(''),[filters,setFilters]=useState(emptyDoctorFilters),[sort,setSort]=useState('name'),[presets,setPresets]=useState([]),[presetName,setPresetName]=useState(''),[ready,setReady]=useState(false),[message,setMessage]=useState(''),[panel,setPanel]=useState(null),[limit,setLimit]=useState(24);
  const lastReset=useRef(resetVersion),filterButton=useRef(null),viewButton=useRef(null);
  useEffect(()=>{try{const saved=JSON.parse(localStorage.getItem(key)||'null');if(saved){if(validFilters(saved.filters))setFilters(saved.filters);if(typeof saved.search==='string')setSearch(saved.search);if(['name','potential','prescriber'].includes(saved.sort))setSort(saved.sort);if(Array.isArray(saved.presets))setPresets(saved.presets.filter(p=>typeof p.id==='string'&&typeof p.name==='string'&&validFilters(p.filters)));}}catch{}setReady(true);},[]);
  useEffect(()=>{if(ready)try{localStorage.setItem(key,JSON.stringify({filters,search,sort,presets}));}catch{}},[ready,filters,search,sort,presets]);
  useEffect(()=>{if(lastReset.current!==resetVersion){lastReset.current=resetVersion;setFilters(emptyDoctorFilters());setSearch('');setPanel(null);}},[resetVersion]);
  const result=useMemo(()=>doctorDirectory(data,{search,filters,sort}),[data,search,filters,sort]);
  const pharmacyNames=useMemo(()=>new Map(data.PHARMACIES.map(p=>[p.Pharmacy_ID,p.Pharmacy_Name])),[data.PHARMACIES]);
  useEffect(()=>{setLimit(24);},[search,filters,sort]);
  const count=Object.values(filters).reduce((total,values)=>total+values.length,0),status=filters.Prescriber_Status.length===1?filters.Prescriber_Status[0]:'';
  function toggle(field,value){setFilters(current=>({...current,[field]:current[field].includes(value)?current[field].filter(v=>v!==value):[...current[field],value]}));}
  function clear(){setSearch('');setFilters(emptyDoctorFilters());}
  function closePanel(){(panel==='filters'?filterButton:viewButton).current?.focus();setPanel(null);}
  return <section className="panel doctor-directory" aria-label="Doctor directory">
    <header className="directory-heading"><div><p className="field-eyebrow">Doctor directory</p><h2>Find a doctor. See the full picture.</h2><p>Search by name, specialty, location, pharmacy or linked product.</p></div><button className="field-primary" onClick={onAdd}><Icon kind="plus"/>Add doctor</button></header>
    <div className="directory-search-row"><div className="directory-search"><Icon kind="search"/><input aria-label="Search doctors" type="search" placeholder="Search your doctors…" value={search} onChange={e=>setSearch(e.target.value)}/></div><button ref={filterButton} className={'field-secondary '+(panel==='filters'?'is-selected':'')} aria-expanded={panel==='filters'} aria-controls="doctor-filter-panel" onClick={()=>setPanel(panel==='filters'?null:'filters')}><Icon kind="filter"/>Filters{!!count&&<span className="field-count">{count}</span>}</button><button ref={viewButton} className={'field-secondary '+(panel==='views'?'is-selected':'')} aria-expanded={panel==='views'} aria-controls="doctor-saved-views" onClick={()=>setPanel(panel==='views'?null:'views')}><Icon kind="bookmark"/>Saved views</button></div>
    {!!count&&<div className="directory-chips">{result.groups.flatMap(group=>filters[group.field].map(value=><button key={group.field+value} onClick={()=>toggle(group.field,value)} aria-label={'Remove '+group.label+' filter '+(group.items.find(item=>item.value===value)?.label||value)}>{group.label}: {group.items.find(item=>item.value===value)?.label||value}<span aria-hidden="true">×</span></button>))}<button className="clear-chip" onClick={clear}>Clear all</button></div>}
    {panel==='filters'&&<section id="doctor-filter-panel" className="directory-filter-panel"><header className="field-section-heading"><div><h3>Narrow your directory</h3><p>Choose several values in any filter.</p></div><button className="field-icon-button" aria-label="Close filters" onClick={closePanel}>×</button></header><div className="directory-filter-grid">{result.groups.map(group=><fieldset key={group.field}><legend>{group.label}{!!filters[group.field].length&&<span className="field-count">{filters[group.field].length}</span>}</legend><div className="directory-options">{group.items.map(item=><label key={item.value}><input type="checkbox" checked={filters[group.field].includes(item.value)} onChange={()=>toggle(group.field,item.value)}/><span>{item.label}</span><small>{item.count}</small></label>)}{!group.items.length&&<small>No values recorded.</small>}</div></fieldset>)}</div><div className="directory-filter-footer"><small>Counts reflect your search and the other filters.</small><button className="text-button" onClick={clear}>Reset selection</button><button className="field-primary" onClick={closePanel}>Show {result.metrics.total} doctors</button></div></section>}
    {panel==='views'&&<section id="doctor-saved-views" className="directory-saved-views"><header className="field-section-heading"><div><h3>Saved views</h3><p>Keep useful selections on this device.</p></div><button className="field-icon-button" aria-label="Close saved views" onClick={closePanel}>×</button></header><div className="directory-preset-list">{presets.map(p=><div key={p.id}><button className="field-secondary" onClick={()=>{setFilters(p.filters);setSearch(p.search||'');setSort(['name','potential','prescriber'].includes(p.sort)?p.sort:'name');closePanel();}}><Icon kind="bookmark"/>{p.name}</button><button className="field-icon-button" aria-label={'Delete saved view '+p.name} onClick={()=>setPresets(current=>current.filter(item=>item.id!==p.id))}>×</button></div>)}{!presets.length&&<p>No saved views yet. Save your current search and filters below.</p>}</div><div className="directory-save-view"><label>Name this view<input value={presetName} maxLength={80} onChange={e=>setPresetName(e.target.value)} placeholder="For example: Camp A prescribers"/></label><button className="field-primary" disabled={!presetName.trim()} onClick={()=>{const name=presetName.trim();setPresets(current=>[...current.filter(p=>p.name!==name),{id:crypto.randomUUID(),name,filters,search,sort}]);setPresetName('');setMessage('View saved on this device.');}}>Save view</button></div></section>}
    {message&&<p role="status" className="scope-note">{message}</p>}
    <div className="directory-results-bar"><div className="directory-quick-tabs" aria-label="Prescriber filter">{[['','All doctors'],['Rx','Rx'],['NRx','NRx']].map(([value,title])=><button key={title} aria-pressed={value?status===value:!filters.Prescriber_Status.length} onClick={()=>setFilters(current=>({...current,Prescriber_Status:value?[value]:[]}))}>{title}</button>)}</div><label>Sort by<select value={sort} onChange={e=>setSort(e.target.value)}><option value="name">Name</option><option value="potential">Potential</option><option value="prescriber">Prescribers first</option></select></label></div>
    <div className="directory-result-count" aria-live="polite"><strong>{result.metrics.total} {result.metrics.total===1?'doctor':'doctors'}</strong><span>{result.metrics.hospitals} hospitals · {result.metrics.pharmacies} pharmacies</span>{!!search&&<button className="text-button" onClick={()=>setSearch('')}>Clear search</button>}</div>
    {doctorId&&!result.doctors.some(d=>d.Doctor_ID===doctorId)&&<p className="scope-note">The open doctor is outside this selection.</p>}
    <div className="doctor-card-grid">{result.doctors.slice(0,limit).map(d=>{const products=result.productNames.get(d.Doctor_ID)||[];return <button className={'doctor-card '+(doctorId===d.Doctor_ID?'selected ':'')+(d.Active==='NO'?'inactive':'')} key={d.Doctor_ID} type="button" aria-pressed={doctorId===d.Doctor_ID} onClick={()=>onSelect(d.Doctor_ID)}><span className="doctor-card-top"><span className="doctor-avatar" aria-hidden="true">{doctorInitials(d.Doctor_Name)}</span><span className={'doctor-status '+(d.Prescriber_Status==='Rx'?'rx':'')}>{d.Prescriber_Status||'Unclassified'}</span><Icon kind="arrow"/></span><strong className="doctor-card-name">{d.Doctor_Name}</strong><span className="doctor-card-specialty">{d.Specialties||'Specialty not specified'}</span>{d.Hospital&&<span className="doctor-card-hospital">{d.Hospital}</span>}<span className="doctor-card-tags">{d.Camp&&<span>{d.Camp}</span>}{d.Potential&&<span>Potential {d.Potential}</span>}{d.Active==='NO'&&<span>Inactive</span>}</span><span className="doctor-card-pharmacy"><small>Linked pharmacy</small><span>{pharmacyNames.get(d.Pharmacy_ID)||'Not specified'}</span></span><span className="doctor-card-products">{products.slice(0,2).map((name,i)=><span key={name+i}>{name}</span>)}{products.length>2&&<span>+{products.length-2} more</span>}{!products.length&&<small>No products linked yet</small>}</span></button>;})}</div>
    {!!result.doctors.length&&<div className="directory-pagination"><span>Showing {Math.min(limit,result.doctors.length)} of {result.doctors.length}</span>{limit<result.doctors.length&&<button className="field-secondary" onClick={()=>setLimit(value=>value+24)}>Show more doctors</button>}</div>}
    {!result.doctors.length&&<div className="directory-empty"><Icon kind="search"/><h3>No doctors match this selection</h3><p>Try another search or clear the filters.</p><button className="field-secondary" onClick={clear}>Clear search &amp; filters</button></div>}
  </section>;
}
