'use client';
import {useEffect,useRef} from 'react';
import {exact} from './ChartPanel.jsx';
import {doctorInitials} from './DoctorDirectory.jsx';
const date=value=>value?new Date(value+'T12:00:00Z').toLocaleDateString('en-IN',{day:'numeric',month:'short',year:'numeric',timeZone:'Asia/Kolkata'}):'Date not recorded';
const status=value=>({BOOKED:'Booked',PARTIAL:'Part supplied',FULFILLED:'Supplied',CANCELLED:'Cancelled'}[value]||value);
export default function DoctorProfile({doctor,data,onClose,onEdit,onLink,onPOB,onEditLink,onHistory,onEditPOB}){
  const heading=useRef(null);
  useEffect(()=>{heading.current?.focus({preventScroll:true});if(window.matchMedia('(max-width: 760px)').matches)heading.current?.closest('aside')?.scrollIntoView({block:'start'});},[doctor.Doctor_ID]);
  const pharmacy=data.PHARMACIES.find(p=>p.Pharmacy_ID===doctor.Pharmacy_ID),links=data.DOCTOR_PRODUCTS.filter(r=>r.Doctor_ID===doctor.Doctor_ID&&r.Active==='YES'),orders=data.POB_ACTIVITY.filter(r=>r.Doctor_ID===doctor.Doctor_ID).sort((a,b)=>String(b.Booking_Date).localeCompare(String(a.Booking_Date))||String(b.Created_At).localeCompare(String(a.Created_At)));
  const productName=sku=>data.products.find(p=>p.Product_SKU===sku)?.Product_Name||sku;
  return <aside className="panel doctor-profile" aria-label="Selected doctor profile">
    <div className="profile-topline"><button className="text-button" onClick={onClose}>← Back to directory</button></div>
    <header className="profile-heading"><span className="doctor-avatar" aria-hidden="true">{doctorInitials(doctor.Doctor_Name)}</span><div><span className={'doctor-status '+(doctor.Prescriber_Status==='Rx'?'rx':'')}>{doctor.Prescriber_Status||'Unclassified'}</span><h2 ref={heading} tabIndex={-1}>{doctor.Doctor_Name}</h2><p>{doctor.Specialties||'Specialty not specified'}</p></div></header>
    {doctor.Hospital&&<p className="profile-hospital">{doctor.Hospital}</p>}<div className="profile-meta"><span>{doctor.Doctor_ID}</span>{doctor.Camp&&<span>{doctor.Camp}</span>}{doctor.Area&&<span>{doctor.Area}</span>}{doctor.Potential&&<span>Potential {doctor.Potential}</span>}{doctor.Active==='NO'&&<span>Inactive</span>}</div>
    <div className="profile-actions"><button className="field-primary" onClick={onLink}>+ Link products</button><button className="field-secondary" onClick={onEdit}>Edit details</button><button className="field-secondary" onClick={onPOB}>+ POB</button></div>
    <div className="profile-pharmacy"><div><p className="field-eyebrow">Linked pharmacy</p><small>Fixed for this doctor</small></div><strong>{pharmacy?.Pharmacy_Name||'Not specified'}</strong>{pharmacy&&<p>{[pharmacy.Area,pharmacy.Camp].filter(Boolean).join(' · ')}</p>}</div>
    <dl className="profile-facts">{[['OP timing',doctor.OP_Timing],['Call schedule',doctor.Call_Schedule],['Stockist',doctor.Stockist],['Latest POB',orders[0]?date(orders[0].Booking_Date):'None recorded']].map(([title,value])=><div key={title}><dt>{title}</dt><dd>{value||'Not specified'}</dd></div>)}</dl>
    {doctor.Notes&&<div className="profile-notes"><h3>Notes</h3><p>{doctor.Notes}</p></div>}
    <section className="profile-products"><div className="field-section-heading"><h3>Linked products <span className="field-count">{links.length}</span></h3><button className="text-button" onClick={onLink}>Add</button></div>{links.map(link=><article key={link.Link_ID}><div><h4>{productName(link.Product_SKU)}</h4><span className={'relationship-badge '+(link.Relationship==='DISCUSSION'?'discussion':'')}>{link.Relationship==='EXISTING'?'Existing':link.Relationship==='DISCUSSION'?'To discuss':'Other'}</span></div>{link.Notes&&<p>{link.Notes}</p>}<button className="text-button" aria-label={'Edit link for '+productName(link.Product_SKU)} onClick={()=>onEditLink(link)}>Edit link</button></article>)}{!links.length&&<div className="profile-empty"><p>Link the products this doctor prescribes or the ones you want to discuss.</p><button className="text-button" onClick={onLink}>Choose products →</button></div>}</section>
    <section className="profile-orders"><div className="field-section-heading"><h3>Recent POBs <span className="field-count">{orders.length}</span></h3>{!!orders.length&&<button className="text-button" onClick={onHistory}>View all</button>}</div>{orders.slice(0,3).map(order=><button key={order.POB_ID} className="profile-order" aria-label={'Edit POB for '+productName(order.Product_SKU)+' booked '+date(order.Booking_Date)} onClick={()=>onEditPOB(order)}><span><strong>{productName(order.Product_SKU)}</strong><small>{date(order.Booking_Date)} · {exact(order.Booked_Units)} {String(order.Quantity_Unit).toLowerCase().replaceAll('_',' ')}</small></span><span className={'pob-status '+order.Status.toLowerCase()}>{status(order.Status)}</span></button>)}{!orders.length&&<div className="profile-empty"><p>No POBs recorded for this doctor.</p><button className="text-button" onClick={onPOB}>Record a POB →</button></div>}</section>
  </aside>;
}
