'use client';
import {useEffect,useRef,useState} from 'react';
import {DataTable,exact} from './ChartPanel.jsx';
import {FIELD_SPEC,QUANTITY_UNITS,indiaToday,DOCTOR_OPTION_COLUMNS,splitSpecialties,nextDoctorId} from '../lib/field-tracking.js';
import DoctorDirectory from './DoctorDirectory.jsx';
import DoctorProfile from './DoctorProfile.jsx';
import {createFieldSession} from '../lib/field-session.js';
const sections=[['doctors','Doctors'],['POB_ACTIVITY','POBs']];
const names={DOCTORS:'Doctor',DOCTOR_PRODUCTS:'Product link',POB_ACTIVITY:'POB'};
const titles={Doctor_ID:'Doctor',Pharmacy_ID:'Pharmacy',Product_SKU:'Product',Quantity_Unit:'Quantity unit',Active:'Active'};
const label=h=>titles[h]||h.replaceAll('_',' ');
const date=v=>v?new Date(v+'T12:00:00Z').toLocaleDateString('en-IN',{day:'2-digit',month:'short',year:'numeric',timeZone:'Asia/Kolkata'}):'Date unknown';
const formGroups={
  DOCTORS:[['Identity','Name, specialties and prescriber status.',['Doctor_Name','Specialties','Prescriber_Status','Potential','Active']],['Location','Enter the pharmacy name and choose the doctor’s location.',['Hospital','Area','Camp','Pharmacy_ID']],['Working details','Keep useful reference information in one place.',['Stockist','OP_Timing','Call_Schedule']],['Notes','Anything else you want to remember.',['Notes']]],
  DOCTOR_PRODUCTS:[['Doctor & pharmacy','Products stay attached to this doctor and their fixed pharmacy.',['Doctor_ID','Pharmacy_ID']],['Products','Choose products from your existing catalogue.',['Product_SKU']],['Relationship','Set the relationship and dates for this link.',['Relationship','Start_Date','End_Date','Active']],['Notes','Shared across the products selected in this entry.',['Notes']]],
  POB_ACTIVITY:[['Doctor & pharmacy','Select the source of this booking.',['Doctor_ID','Pharmacy_ID','Agency']],['Booking','Record the product, quantity and booking date.',['Product_SKU','Booked_Units','Quantity_Unit','Booking_Date']],['Supply','Record supplied quantities when they are confirmed.',['Status','Fulfilled_Units','Fulfilled_Date']],['Notes','Keep any useful booking details here.',['Notes']]]
};
async function request(body){const response=await fetch('/api/fields',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body),cache:'no-store',signal:AbortSignal.timeout(60000)});let result;try{result=await response.json();}catch{throw new Error('The field-data connection returned an invalid response. Your entry is kept in the form.');}if(!response.ok)throw new Error(result.error||'Could not load field data.');return result;}
export default function FieldWorkspace({visible,refreshVersion,onLoadingChange}){
  const [data,setData]=useState(null),[loading,setLoading]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
  const [section,setSection]=useState('doctors'),[doctorId,setDoctorId]=useState(''),[directoryReset,setDirectoryReset]=useState(0);
  const [scope,setScope]=useState({product:'',pharmacy:'',start:'',end:''});
  const [links,setLinks]=useState([]),[productSearch,setProductSearch]=useState('');
  const [editor,setEditor]=useState(null),[record,setRecord]=useState({}),[saving,setSaving]=useState(false);
  const [pharmacyName,setPharmacyName]=useState('');
  const [session]=useState(()=>createFieldSession(force=>request({action:'read',force}).then(r=>r.data),()=>localStorage));
  const loadedVersion=useRef(-1),readEpoch=useRef(0),editorElement=useRef(null),editorOrigin=useRef(null),editorInitial=useRef(''),doctorOrigin=useRef(null),today=indiaToday();
  useEffect(()=>{if(!visible||loadedVersion.current===refreshVersion)return;loadedVersion.current=refreshVersion;const epoch=++readEpoch.current;setError('');if(refreshVersion===0){const cached=session.restore();if(cached){setData(cached);setLoading(false);return;}}setLoading(true);session.load(refreshVersion>0).then(value=>{if(epoch===readEpoch.current){setData(value);setNotice('');}}).catch(e=>{if(epoch===readEpoch.current)setError('Refresh failed; the previous saved data is still shown. '+e.message);}).finally(()=>{if(epoch===readEpoch.current)setLoading(false);});},[visible,refreshVersion,session]);
  useEffect(()=>{onLoadingChange?.(visible&&loading);},[visible,loading,onLoadingChange]);
  useEffect(()=>{if(editor)editorElement.current?.querySelector('input,select,textarea')?.focus();else editorOrigin.current?.focus();},[editor]);
  function open(table,existing){const spec=FIELD_SPEC[table],r=Object.fromEntries(spec.headers.map(h=>[h,existing?.[h]??'']));r[spec.headers[0]]=existing?.[spec.headers[0]]||(table==='DOCTORS'?'':crypto.randomUUID());
    if(!existing){if(table!=='DOCTORS'&&spec.headers.includes('Doctor_ID'))r.Doctor_ID=doctorId;if(spec.headers.includes('Pharmacy_ID'))r.Pharmacy_ID=scope.pharmacy||data.DOCTORS.find(d=>d.Doctor_ID===doctorId)?.Pharmacy_ID||'';if(spec.headers.includes('Product_SKU'))r.Product_SKU=scope.product;
      for(const h of ['Booking_Date'])if(spec.headers.includes(h))r[h]=today;
      if(table==='DOCTORS'){r.Pharmacy_ID='';r.Prescriber_Status='NRx';}if(table==='POB_ACTIVITY')r.Status='BOOKED';
      if(spec.headers.includes('Active'))r.Active='YES';if(table==='DOCTOR_PRODUCTS')r.Relationship='EXISTING';
    }if(r.Doctor_ID&&table!=='DOCTORS')r.Pharmacy_ID=data.DOCTORS.find(d=>d.Doctor_ID===r.Doctor_ID)?.Pharmacy_ID||'';const pharmacy=table==='DOCTORS'?data.PHARMACIES.find(p=>p.Pharmacy_ID===r.Pharmacy_ID)?.Pharmacy_Name||'':'';setPharmacyName(pharmacy);setLinks(table==='DOCTOR_PRODUCTS'&&!existing&&r.Product_SKU?[{Link_ID:r.Link_ID,Product_SKU:r.Product_SKU}]:[]);setProductSearch('');editorInitial.current=JSON.stringify({record:r,links:table==='DOCTOR_PRODUCTS'&&!existing&&r.Product_SKU?[{Link_ID:r.Link_ID,Product_SKU:r.Product_SKU}]:[],pharmacyName:pharmacy});editorOrigin.current=document.activeElement;setRecord(r);setEditor({table,operation:existing?'update':'create',previous:existing,...(table==='DOCTORS'&&!existing?{requestId:crypto.randomUUID()}:{})});setError('');setNotice('');}
  async function save(e){e.preventDefault();setSaving(true);setError('');try{const result=await request({action:'save',...editor,record:editor.table==='DOCTOR_PRODUCTS'&&editor.operation==='create'?{...record,Product_SKU:''}:record,...(editor.table==='DOCTORS'?{pharmacyName}:{}),...(editor.table==='DOCTOR_PRODUCTS'&&editor.operation==='create'?{links}: {})});if(editor.table==='DOCTOR_PRODUCTS'&&editor.operation==='create'&&!Array.isArray(result.records))throw new Error('Update the existing Apps Script deployment with the new Code.gs before saving multiple products.');setData(session.saved(editor.table,result.records||result.record,result.pharmacies||[]));setNotice(names[editor.table]+' saved.'+(editor.table==='DOCTORS'?' ID: '+result.record.Doctor_ID:''));if(editor.table==='DOCTORS'){setDoctorId(result.record.Doctor_ID);setScope({product:'',pharmacy:'',start:'',end:''});setDirectoryReset(v=>v+1);}setEditor(null);}catch(e){setError(e.message);}finally{setSaving(false);}}
  if(!visible)return null;
  if(!data)return <section className="panel field-workspace"><h2>Doctor &amp; pharmacy workspace</h2><p role="status">{loading?'Loading doctors, pharmacies and your activity logs…':'Tracking data has not loaded.'}</p>{error&&<p className="message error" role="alert">{error}</p>}<button className="button" disabled={loading} onClick={()=>{loadedVersion.current=refreshVersion;const epoch=++readEpoch.current;setLoading(true);setError('');session.load(true).then(value=>{if(epoch===readEpoch.current)setData(value);}).catch(e=>{if(epoch===readEpoch.current)setError('Refresh failed; the previous saved data is still shown. '+e.message);}).finally(()=>{if(epoch===readEpoch.current)setLoading(false);});}}>Retry connection</button></section>;
  const doctor=data.DOCTORS.find(d=>d.Doctor_ID===doctorId);
  const doctorName=id=>data.DOCTORS.find(d=>d.Doctor_ID===id)?.Doctor_Name||id||'—';
  const pharmacyLabel=id=>data.PHARMACIES.find(p=>p.Pharmacy_ID===id)?.Pharmacy_Name||id||'—';
  const productName=sku=>data.products.find(p=>p.Product_SKU===sku)?.Product_Name||sku||'General';
  const matches=r=>(!doctorId||r.Doctor_ID===doctorId)&&(!scope.pharmacy||r.Pharmacy_ID===scope.pharmacy)&&(!scope.product||r.Product_SKU===scope.product);
  const inPeriod=(r,key)=>{const d=r[key];return (!scope.start||d&&d>=scope.start)&&(!scope.end||d&&d<=scope.end);};
  const activityTable=section==='doctors'?'POB_ACTIVITY':section;
  const rows=(data[activityTable]||[]).filter(r=>matches(r)&&inPeriod(r,'Booking_Date')).sort((a,b)=>String(b.Booking_Date).localeCompare(String(a.Booking_Date)));
  const columns=[{label:'Doctor',render:r=>doctorName(r.Doctor_ID)},{label:'Pharmacy',render:r=>pharmacyLabel(r.Pharmacy_ID)},{label:'Product',render:r=>productName(r.Product_SKU)}];
  if(activityTable==='POB_ACTIVITY')columns.push({label:'Booked',render:r=>date(r.Booking_Date)},{label:'Booked units',render:r=>exact(r.Booked_Units)+' '+r.Quantity_Unit},{label:'Supplied units',render:r=>r.Fulfilled_Units===''?'Unknown':exact(r.Fulfilled_Units)+' '+r.Quantity_Unit},{label:'Status',key:'Status'});
  columns.push({label:'Notes',key:'Notes'},{label:'Action',render:r=><button className="text-button" onClick={()=>open(activityTable,r)}>Edit</button>});
  function closeEditor(){if(saving)return;if(JSON.stringify({record,links,pharmacyName})===editorInitial.current||window.confirm('Discard your unsaved changes?'))setEditor(null);}
  function renderField(h){
      const spec=FIELD_SPEC[editor.table],required=spec.required.includes(h),doctorOptions=editor.table==='DOCTORS'?data.options?.[DOCTOR_OPTION_COLUMNS[h]]:null,choices=spec.options?.[h]||(h==='Quantity_Unit'?QUANTITY_UNITS:h==='Agency'?data.agencies:editor.table==='DOCTORS'&&['Area','Camp','Potential'].includes(h)?doctorOptions:null),value=record[h]??'';
      if(h==='Pharmacy_ID'&&record.Doctor_ID&&(editor.table!=='DOCTORS'||editor.previous?.Pharmacy_ID))return <label key={h}>Linked pharmacy<input readOnly value={data.PHARMACIES.find(p=>p.Pharmacy_ID===(editor.table==='DOCTORS'?editor.previous.Pharmacy_ID:data.DOCTORS.find(d=>d.Doctor_ID===record.Doctor_ID)?.Pharmacy_ID))?.Pharmacy_Name||'No linked pharmacy in doctor master'}/><small>Fixed for this doctor.</small></label>;
      if(h==='Pharmacy_ID'&&editor.table==='DOCTORS')return <label key={h}>Pharmacy *<input required type="text" value={pharmacyName} onChange={e=>setPharmacyName(e.target.value)} maxLength={2000} placeholder="Enter the pharmacy name"/><small>Saved with this doctor. A matching name, area and camp reuses the same pharmacy.</small></label>;
      if(h==='Camp'&&editor.table==='DOCTORS'&&editor.operation==='update')return <label key={h}>Camp<input readOnly value={value}/><small>Camp is fixed because it identifies this doctor’s ID.</small></label>;
      const change=e=>{const v=e.target.value;setRecord(r=>{const next={...r,[h]:v};if(h==='Doctor_ID')next.Pharmacy_ID=data.DOCTORS.find(d=>d.Doctor_ID===v)?.Pharmacy_ID||'';return next;});};
      if(h==='Product_SKU'&&editor.table==='DOCTOR_PRODUCTS'&&editor.operation==='create')return <fieldset key={h} className="field-wide product-picker"><legend>Products * · {links.length} selected</legend><input type="search" aria-label="Find products to link" placeholder="Find a product" value={productSearch} onChange={e=>setProductSearch(e.target.value)}/><div className="product-picker-list">{data.products.filter(p=>(p.Product_Name+' '+p.Product_SKU).toLowerCase().includes(productSearch.toLowerCase())).map(p=><label key={p.Product_SKU}><input type="checkbox" checked={links.some(l=>l.Product_SKU===p.Product_SKU)} onChange={e=>setLinks(current=>e.target.checked?[...current,{Link_ID:crypto.randomUUID(),Product_SKU:p.Product_SKU}]:current.filter(l=>l.Product_SKU!==p.Product_SKU))}/><span>{p.Product_Name}<small>{p.Product_SKU}</small></span></label>)}</div><small>The relationship, pharmacy, dates and notes apply to each selected product.</small></fieldset>;
      const entities=h==='Doctor_ID'?data.DOCTORS.map(d=>[d.Doctor_ID,d.Doctor_Name+' · '+d.Camp]):h==='Pharmacy_ID'?data.PHARMACIES.map(p=>[p.Pharmacy_ID,p.Pharmacy_Name+' · '+p.Area+' · '+p.Camp]):h==='Product_SKU'?data.products.map(p=>[p.Product_SKU,p.Product_Name+' · '+p.Product_SKU+(p.Active?'':' · historical')]):null;
      if(h==='Specialties'&&editor.table==='DOCTORS'){const selected=splitSpecialties(value),options=[...new Set([...(doctorOptions||[]),...selected])];return <fieldset key={h} className="field-wide doctor-specialty-picker"><legend>Specialties · {selected.length} selected</legend><div className="doctor-specialty-options">{options.map(option=><label key={option}><input type="checkbox" checked={selected.includes(option)} onChange={e=>setRecord(r=>({...r,Specialties:(e.target.checked?[...splitSpecialties(r.Specialties),option]:splitSpecialties(r.Specialties).filter(v=>v!==option)).join(', ')}))}/><span>{option}</span></label>)}</div><small>Select all specialties that apply.</small></fieldset>;}
      if(editor.table==='DOCTORS'&&['OP_Timing','Call_Schedule'].includes(h))return <label key={h}>{label(h)}<input list={'doctor-options-'+h} value={value} onChange={change} maxLength={2000}/><datalist id={'doctor-options-'+h}>{(doctorOptions||[]).map(v=><option key={v} value={v}/>)}</datalist></label>;
      const fieldChoices=choices&&value&&!choices.includes(value)&&editor.table==='DOCTORS'&&h!=='Stockist'?[value,...choices]:choices;
      return <label key={h} className={h==='Notes'?'field-wide':''}>{label(h)}{required?' *':''}{h==='Notes'?<textarea autoFocus={false} value={value} onChange={change} maxLength={2000}/>:entities||fieldChoices?<select required={required} value={value} onChange={change}><option value="">{required?'Choose…':'Not specified'}</option>{(entities||fieldChoices.map(c=>[c,label(c)])).map(([v,n])=><option key={v} value={v}>{n}</option>)}</select>:<input required={required} value={value} onChange={change} type={spec.dates?.includes(h)?'date':spec.numbers?.includes(h)?'number':'text'} min={spec.numbers?.includes(h)?0:undefined} step={spec.numbers?.includes(h)?'any':undefined} maxLength={2000} max={['Booking_Date','Fulfilled_Date'].includes(h)?today:undefined}/>}</label>;

  }
  function selectDoctor(id){doctorOrigin.current=document.activeElement;setDoctorId(id);setScope({product:'',pharmacy:'',start:'',end:''});}
  function closeProfile(){setDoctorId('');requestAnimationFrame(()=>doctorOrigin.current?.focus());}
  return <section className="field-workspace" aria-busy={loading}>
    <div className="field-workspace-tabs" aria-label="Tracking sections">{sections.map(([key,title])=><button type="button" key={key} aria-pressed={section===key} onClick={()=>setSection(key)}>{title}<span>{key==='doctors'?data.DOCTORS.length:data.POB_ACTIVITY.length}</span></button>)}</div>
    {error&&!editor&&<p className="message error" role="alert">{error}</p>}{notice&&<p className="message" role="status">{notice}</p>}
    <div hidden={section!=='doctors'} className={'field-doctor-layout '+(doctor?'has-profile':'')}>
      <DoctorDirectory data={data} doctorId={doctorId} onSelect={selectDoctor} onAdd={()=>open('DOCTORS')} resetVersion={directoryReset}/>
      {section==='doctors'&&doctor&&<DoctorProfile doctor={doctor} data={data} onClose={closeProfile} onEdit={()=>open('DOCTORS',doctor)} onLink={()=>open('DOCTOR_PRODUCTS')} onPOB={()=>open('POB_ACTIVITY')} onEditLink={r=>open('DOCTOR_PRODUCTS',r)} onHistory={()=>{setScope({product:'',pharmacy:'',start:'',end:''});setSection('POB_ACTIVITY');}} onEditPOB={r=>open('POB_ACTIVITY',r)}/>}
    </div>
    {section==='POB_ACTIVITY'&&<section className="panel field-pob-view">
      <header className="directory-heading"><div><p className="field-eyebrow">Booking history</p><h2>POBs, in one place.</h2><p>Review booked products, quantities and confirmed supplies.</p></div><button className="field-primary" onClick={()=>open('POB_ACTIVITY')}>+ Record POB</button></header>
      <div className="field-scope"><label>Doctor<select value={doctorId} onChange={e=>{setDoctorId(e.target.value);setScope(s=>({...s,pharmacy:''}));}}><option value="">All doctors</option>{data.DOCTORS.map(d=><option key={d.Doctor_ID} value={d.Doctor_ID}>{d.Doctor_Name} · {d.Camp}</option>)}</select></label><label>Pharmacy<select disabled={!!doctor} value={doctor?.Pharmacy_ID||scope.pharmacy} onChange={e=>setScope(s=>({...s,pharmacy:e.target.value}))}><option value="">{doctor?'Linked pharmacy':'All pharmacies'}</option>{data.PHARMACIES.map(p=><option key={p.Pharmacy_ID} value={p.Pharmacy_ID}>{p.Pharmacy_Name} · {p.Area} · {p.Camp}</option>)}</select></label><label>Product<select value={scope.product} onChange={e=>setScope(s=>({...s,product:e.target.value}))}><option value="">All products</option>{data.products.map(p=><option key={p.Product_SKU} value={p.Product_SKU}>{p.Product_Name} · {p.Product_SKU}{p.Active?'':' · historical'}</option>)}</select></label><label>From<input type="date" value={scope.start} max={scope.end||undefined} onChange={e=>setScope(s=>({...s,start:e.target.value}))}/></label><label>To<input type="date" value={scope.end} min={scope.start||undefined} onChange={e=>setScope(s=>({...s,end:e.target.value}))}/></label><button className="text-button" onClick={()=>{setDoctorId('');setScope({product:'',pharmacy:'',start:'',end:''});}}>Reset filters</button></div>
      <div className="field-section-heading"><h3>{rows.length} {rows.length===1?'entry':'entries'}</h3><span className="scope-note">Latest bookings first</span></div>
      <DataTable columns={columns} rows={rows} empty="No POBs match this selection. Change the filters or record a new booking."/>
    </section>}
    {editor&&<div className="field-modal-backdrop"><section ref={editorElement} onKeyDown={e=>{if(e.key==='Escape'){e.stopPropagation();closeEditor();}if(e.key==='Tab'){const nodes=[...editorElement.current.querySelectorAll('button,input,select,textarea')].filter(node=>!node.matches(':disabled'));const first=nodes[0],last=nodes.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}}} className="field-editor panel" role="dialog" aria-modal="true" aria-labelledby="field-editor-title" aria-describedby="field-editor-description">
      <header className="field-editor-header"><div><p className="field-eyebrow">{editor.table==='DOCTORS'?'Doctor directory':editor.table==='DOCTOR_PRODUCTS'?'Product relationships':'Booking history'}</p><h2 id="field-editor-title">{editor.operation==='update'?'Edit':editor.table==='DOCTORS'?'Add':'Record'} {editor.table==='DOCTOR_PRODUCTS'&&editor.operation==='create'?'product links':names[editor.table].toLowerCase()}</h2><p id="field-editor-description">{editor.table==='DOCTORS'?'Keep the doctor profile complete and easy to find.':editor.table==='DOCTOR_PRODUCTS'?'Connect the right products to this doctor.':'Track the booking and its confirmed supply.'}</p></div><button className="field-icon-button" disabled={saving} aria-label="Close form" onClick={closeEditor}>×</button></header>
      <form onSubmit={save}><div className="field-editor-body">{error&&<p className="message error" role="alert">{error}</p>}{editor.table==='DOCTORS'&&<p className="scope-note doctor-id-note">Doctor ID: {record.Doctor_ID||(()=>{try{return record.Camp?nextDoctorId(record.Camp,data.DOCTORS)+' · assigned on save':'Choose a camp to see its ID sequence.';}catch(e){return e.message;}})()}{!record.Doctor_ID&&record.Camp&&<small>The final number is allocated when saved.</small>}</p>}<fieldset className="field-editable-fields" disabled={saving}>{formGroups[editor.table].map(([title,description,fields],i)=><section key={title} className="field-form-section"><header><span>{String(i+1).padStart(2,'0')}</span><div><h3>{title}</h3><p>{description}</p></div></header><div className="field-form-grid">{fields.map(renderField)}</div></section>)}</fieldset></div>
      <div className="field-editor-footer"><p role={saving?'status':undefined}>{saving?'Saving your entry…':'* Required fields'}</p><button className="field-secondary" disabled={saving} type="button" onClick={closeEditor}>Cancel</button><button className="field-primary" disabled={saving||(editor.table==='DOCTOR_PRODUCTS'&&editor.operation==='create'&&!links.length)} type="submit">{saving?'Saving…':'Save'}</button></div></form>
    </section></div>}
    {loading&&<p className="message" role="status">Refreshing doctor and pharmacy data from the sheet…</p>}
  </section>;
}
