'use client';
import {useEffect,useRef,useState} from 'react';
import ChartPanel,{DataTable,exact,monthLabel} from './ChartPanel.jsx';
import {FIELD_SPEC,QUANTITY_UNITS,indiaToday,latestPharmacyStock,targetActual} from '../lib/field-tracking.js';
import {createFieldSession} from '../lib/field-session.js';

const sections=[['doctors','Doctors'],['RX_ACTIVITY','Prescriptions'],['PHARMACY_STOCK_CHECKS','Pharmacy stock'],['FOLLOW_UPS','Follow-ups'],['POB_ACTIVITY','POBs'],['TARGETS','Targets']];
const names={DOCTOR_PRODUCTS:'Product link',RX_ACTIVITY:'Prescription',PHARMACY_STOCK_CHECKS:'Stock check',FOLLOW_UPS:'Follow-up',POB_ACTIVITY:'POB',TARGETS:'Target'};
const titles={Rx_ID:'ID',Prescription_Date:'Prescription date (if known)',Reported_Date:'Date reported',Doctor_ID:'Doctor',Pharmacy_ID:'Pharmacy',Product_SKU:'Product',Quantity:'Quantity (if known)',Quantity_Unit:'Quantity unit',Confirmation:'Evidence',Remaining_Units:'Remaining units',Source:'Stock information from',Metric:'Target metric',Target_Value:'Target amount',Scope:'Target scope',Month:'Target month',Active:'Active'};
const label=h=>titles[h]||h.replaceAll('_',' ');
const date=v=>v?new Date(v+'T12:00:00Z').toLocaleDateString('en-IN',{day:'2-digit',month:'short',year:'numeric',timeZone:'Asia/Kolkata'}):'Date unknown';
const days=(v,today)=>v?Math.floor((Date.parse(today+'T12:00:00Z')-Date.parse(v+'T12:00:00Z'))/86400000):null;
async function request(body){const response=await fetch('/api/fields',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body),cache:'no-store',signal:AbortSignal.timeout(60000)});let result;try{result=await response.json();}catch{throw new Error('The field-data connection returned an invalid response. Your entry is kept in the form.');}if(!response.ok)throw new Error(result.error||'Could not load field data.');return result;}

export default function FieldWorkspace({visible,refreshVersion,monthly=[]}){
  const [data,setData]=useState(null),[loading,setLoading]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
  const [section,setSection]=useState('doctors'),[doctorId,setDoctorId]=useState(''),[search,setSearch]=useState(''),[camp,setCamp]=useState(''),[potential,setPotential]=useState('');
  const [scope,setScope]=useState({product:'',pharmacy:'',start:'',end:''}),[staleDays,setStaleDays]=useState(14),[showClosed,setShowClosed]=useState(false);
  const [editor,setEditor]=useState(null),[record,setRecord]=useState({}),[saving,setSaving]=useState(false);
  const [session]=useState(()=>createFieldSession(()=>request({action:'read'}).then(r=>r.data),()=>localStorage));
  const loadedVersion=useRef(-1),readEpoch=useRef(0),editorElement=useRef(null),editorOrigin=useRef(null),today=indiaToday();
  useEffect(()=>{if(!visible||loadedVersion.current===refreshVersion)return;loadedVersion.current=refreshVersion;const epoch=++readEpoch.current;setError('');if(refreshVersion===0){const cached=session.restore();if(cached){setData(cached);setLoading(false);return;}}setLoading(true);session.load(refreshVersion>0).then(value=>{if(epoch===readEpoch.current){setData(value);setNotice('');}}).catch(e=>{if(epoch===readEpoch.current)setError(e.message);}).finally(()=>{if(epoch===readEpoch.current)setLoading(false);});},[visible,refreshVersion,session]);
  useEffect(()=>{if(editor)editorElement.current?.querySelector('input,select,textarea')?.focus();else editorOrigin.current?.focus();},[editor]);
  function open(table,existing){const spec=FIELD_SPEC[table],r=Object.fromEntries(spec.headers.map(h=>[h,existing?.[h]??'']));r[spec.headers[0]]=existing?.[spec.headers[0]]||crypto.randomUUID();
    if(!existing){if(spec.headers.includes('Doctor_ID'))r.Doctor_ID=doctorId;if(spec.headers.includes('Pharmacy_ID'))r.Pharmacy_ID=scope.pharmacy||data.DOCTORS.find(d=>d.Doctor_ID===doctorId)?.Pharmacy_ID||'';if(spec.headers.includes('Product_SKU'))r.Product_SKU=scope.product;
      for(const h of ['Reported_Date','Checked_Date','Booking_Date'])if(spec.headers.includes(h))r[h]=today;
      if(table==='FOLLOW_UPS'){r.Status='OPEN';r.Due_Date=today;r.Reason='PRESCRIPTION_REVIEW';}
      if(table==='RX_ACTIVITY')r.Confirmation='REPORTED';if(table==='PHARMACY_STOCK_CHECKS')r.Source='PHARMACIST';if(table==='POB_ACTIVITY')r.Status='BOOKED';
      if(spec.headers.includes('Active'))r.Active='YES';if(table==='DOCTOR_PRODUCTS')r.Relationship='EXISTING';if(table==='TARGETS'){r.Month=today.slice(0,7);r.Scope='OVERALL';r.Metric='SECONDARY_REVENUE';r.Doctor_ID='';r.Pharmacy_ID='';r.Product_SKU='';}
    }editorOrigin.current=document.activeElement;setRecord(r);setEditor({table,operation:existing?'update':'create',previous:existing});setError('');setNotice('');}
  async function save(e){e.preventDefault();setSaving(true);setError('');try{const result=await request({action:'save',...editor,record});readEpoch.current++;setLoading(false);setData(session.saved(editor.table,result.record));setNotice(names[editor.table]+' saved to Google Sheets.');setEditor(null);}catch(e){setError(e.message);}finally{setSaving(false);}}
  if(!visible)return null;
  if(!data)return <section className="panel field-workspace"><h2>Doctor &amp; pharmacy workspace</h2><p role="status">{loading?'Loading doctors, pharmacies and your activity logs…':'Tracking data has not loaded.'}</p>{error&&<p className="message error" role="alert">{error}</p>}<button className="button" disabled={loading} onClick={()=>{loadedVersion.current=refreshVersion;const epoch=++readEpoch.current;setLoading(true);setError('');session.load(true).then(value=>{if(epoch===readEpoch.current)setData(value);}).catch(e=>{if(epoch===readEpoch.current)setError(e.message);}).finally(()=>{if(epoch===readEpoch.current)setLoading(false);});}}>Retry connection</button></section>;
  const doctor=data.DOCTORS.find(d=>d.Doctor_ID===doctorId),pharmacy=data.PHARMACIES.find(p=>p.Pharmacy_ID===(scope.pharmacy||doctor?.Pharmacy_ID));
  const doctorName=id=>data.DOCTORS.find(d=>d.Doctor_ID===id)?.Doctor_Name||id||'—';
  const pharmacyName=id=>data.PHARMACIES.find(p=>p.Pharmacy_ID===id)?.Pharmacy_Name||id||'—';
  const productName=sku=>data.products.find(p=>p.Product_SKU===sku)?.Product_Name||sku||'General';
  const matches=r=>(!doctorId||r.Doctor_ID===doctorId)&&(!scope.pharmacy||r.Pharmacy_ID===scope.pharmacy)&&(!scope.product||r.Product_SKU===scope.product);
  const inPeriod=(r,key)=>{const d=r[key];return (!scope.start||d&&d>=scope.start)&&(!scope.end||d&&d<=scope.end);};
  const rx=data.RX_ACTIVITY.filter(r=>matches(r)&&inPeriod(r,'Prescription_Date'));
  const followups=data.FOLLOW_UPS.filter(r=>matches(r)&&inPeriod(r,'Due_Date')&&(showClosed||r.Status==='OPEN')).sort((a,b)=>a.Due_Date.localeCompare(b.Due_Date));
  const stock=latestPharmacyStock(data.PHARMACY_STOCK_CHECKS).filter(r=>(!doctorId||!!pharmacy)&&(!pharmacy||r.Pharmacy_ID===pharmacy.Pharmacy_ID)&&(!scope.product||r.Product_SKU===scope.product)&&inPeriod(r,'Checked_Date'));
  const activityTable=section==='doctors'?'RX_ACTIVITY':section;
  const rows=activityTable==='RX_ACTIVITY'?rx:activityTable==='FOLLOW_UPS'?followups:activityTable==='PHARMACY_STOCK_CHECKS'?stock:(data[activityTable]||[]).filter(r=>matches(r)&&(activityTable==='TARGETS'?(!scope.start||r.Month>=scope.start.slice(0,7))&&(!scope.end||r.Month<=scope.end.slice(0,7)):inPeriod(r,'Booking_Date')));
  const lastRx=data.RX_ACTIVITY.filter(r=>r.Doctor_ID===doctorId&&r.Prescription_Date&&(!scope.product||r.Product_SKU===scope.product)).sort((a,b)=>b.Prescription_Date.localeCompare(a.Prescription_Date))[0];
  const due=data.FOLLOW_UPS.filter(r=>matches(r)&&r.Status==='OPEN'&&r.Due_Date<=today);
  const columns=[{label:'Doctor',render:r=>doctorName(r.Doctor_ID)},{label:'Pharmacy',render:r=>pharmacyName(r.Pharmacy_ID)},{label:'Product',render:r=>productName(r.Product_SKU)}];
  if(activityTable==='RX_ACTIVITY')columns.push({label:'Prescription date',render:r=>date(r.Prescription_Date)},{label:'Reported',render:r=>date(r.Reported_Date)},{label:'Quantity',render:r=>r.Quantity===''?'Unknown':exact(r.Quantity)+' '+r.Quantity_Unit},{label:'Evidence',key:'Confirmation'});
  if(activityTable==='PHARMACY_STOCK_CHECKS')columns.splice(0,1),columns.push({label:'Checked',render:r=>date(r.Checked_Date)},{label:'Remaining',render:r=>exact(r.Remaining_Units)+' '+r.Quantity_Unit},{label:'Check age',render:r=>days(r.Checked_Date,today)+' days'+(days(r.Checked_Date,today)>=staleDays?' · Recheck':'')});
  if(activityTable==='FOLLOW_UPS')columns.push({label:'Due',render:r=>date(r.Due_Date)+(r.Status==='OPEN'&&r.Due_Date<=today?' · Due':'')},{label:'Reason',render:r=>label(r.Reason)},{label:'Status',key:'Status'});
  if(activityTable==='POB_ACTIVITY')columns.push({label:'Booked',render:r=>date(r.Booking_Date)},{label:'Booked units',render:r=>exact(r.Booked_Units)+' '+r.Quantity_Unit},{label:'Supplied units',render:r=>r.Fulfilled_Units===''?'Unknown':exact(r.Fulfilled_Units)+' '+r.Quantity_Unit},{label:'Status',key:'Status'});
  if(activityTable==='TARGETS')columns.push({label:'Month',render:r=>monthLabel(r.Month)},{label:'Scope',render:r=>r.Scope+(r.Agency?' · '+r.Agency:'')},{label:'Metric',render:r=>label(r.Metric)},{label:'Target',render:r=>exact(r.Target_Value,r.Metric==='SECONDARY_REVENUE')+(r.Quantity_Unit?' '+r.Quantity_Unit:'')},{label:'Recorded actual',render:r=>exact(targetActual(r,data,monthly),r.Metric==='SECONDARY_REVENUE')},{label:'Gap',render:r=>{const actual=targetActual(r,data,monthly);return actual==null?'Unavailable':exact(Math.max(0,Number(r.Target_Value)-actual),r.Metric==='SECONDARY_REVENUE');}});
  columns.push({label:'Notes',key:'Notes'},{label:'Action',render:r=><button className="text-button" onClick={()=>open(activityTable,r)}>Edit</button>});
  const months=[...new Set(rx.filter(r=>r.Prescription_Date).map(r=>r.Prescription_Date.slice(0,7)))].sort();
  const chartRows=months.map(m=>({month:m,count:rx.filter(r=>r.Prescription_Date?.startsWith(m)).length}));
  const doctors=data.DOCTORS.filter(d=>(!camp||d.Camp===camp)&&(!potential||d.Potential===potential)&&(!search||[d.Doctor_Name,d.Specialties,d.Hospital,d.Area].some(v=>String(v).toLowerCase().includes(search.toLowerCase()))));
  return <section className="field-workspace" aria-busy={loading}>
    <div className="product-report-tabs" aria-label="Tracking sections">{sections.map(([key,title])=><button type="button" key={key} aria-pressed={section===key} onClick={()=>setSection(key)}>{title}</button>)}</div>
    {error&&<p className="message error" role="alert">{error}</p>}{notice&&<p className="message" role="status">{notice}</p>}
    <div className="field-scope panel"><label>Doctor<select value={doctorId} onChange={e=>{setDoctorId(e.target.value);setScope(s=>({...s,pharmacy:''}));}}><option value="">All doctors</option>{data.DOCTORS.map(d=><option key={d.Doctor_ID} value={d.Doctor_ID}>{d.Doctor_Name} · {d.Camp}</option>)}</select></label><label>Pharmacy<select value={scope.pharmacy} onChange={e=>setScope(s=>({...s,pharmacy:e.target.value}))}><option value="">{doctor?'Linked pharmacy':'All pharmacies'}</option>{data.PHARMACIES.map(p=><option key={p.Pharmacy_ID} value={p.Pharmacy_ID}>{p.Pharmacy_Name} · {p.Area} · {p.Camp}</option>)}</select></label><label>Product<select value={scope.product} onChange={e=>setScope(s=>({...s,product:e.target.value}))}><option value="">All products</option>{data.products.map(p=><option key={p.Product_SKU} value={p.Product_SKU}>{p.Product_Name} · {p.Product_SKU}{p.Active?'':' · excluded / historical'}</option>)}</select></label><label>From<input type="date" value={scope.start} onChange={e=>setScope(s=>({...s,start:e.target.value}))}/></label><label>To<input type="date" value={scope.end} min={scope.start||undefined} onChange={e=>setScope(s=>({...s,end:e.target.value}))}/></label><button className="text-button" onClick={()=>{setDoctorId('');setScope({product:'',pharmacy:'',start:'',end:''});}}>Reset</button></div>
    <div className="field-actions">{[['RX_ACTIVITY','+ Prescription'],['PHARMACY_STOCK_CHECKS','+ Stock check'],['FOLLOW_UPS','+ Follow-up'],['POB_ACTIVITY','+ POB'],['TARGETS','+ Target']].map(([table,title])=><button key={table} className="button" onClick={()=>open(table)}>{title}</button>)}</div>
    <section className="kpi-grid field-kpis"><article className="kpi"><p>Prescription product entries</p><strong>{rx.length}</strong><small>Manually logged · quantities may be unknown</small></article><article className="kpi"><p>Follow-ups due</p><strong>{due.length}</strong><small>Open tasks due today or earlier</small></article><article className="kpi"><p>Pharmacy stock checks</p><strong>{stock.length}</strong><small>Latest dated observation per product / unit</small></article><article className="kpi"><p>Stock checks to revisit</p><strong>{stock.filter(r=>days(r.Checked_Date,today)>=staleDays).length}</strong><small>At least {staleDays} days since check</small></article></section>
    {section==='doctors'&&<div className="field-doctor-grid"><aside className="panel"><label>Find a doctor<input type="search" placeholder="Name, specialty, hospital or area" value={search} onChange={e=>setSearch(e.target.value)}/></label><div className="field-scope"><label>Camp<select value={camp} onChange={e=>setCamp(e.target.value)}><option value="">All camps</option>{[...new Set(data.DOCTORS.map(d=>d.Camp))].sort().map(c=><option key={c}>{c}</option>)}</select></label><label>Potential<select value={potential} onChange={e=>setPotential(e.target.value)}><option value="">All</option>{['A','B','C'].map(p=><option key={p}>{p}</option>)}</select></label></div><p>{doctors.length} doctors</p><div className="field-doctor-list">{doctors.map(d=><button key={d.Doctor_ID} type="button" aria-pressed={doctorId===d.Doctor_ID} onClick={()=>{setDoctorId(d.Doctor_ID);setScope(s=>({...s,pharmacy:''}));}}><strong>{d.Doctor_Name}</strong><span>{d.Specialties} · {d.Camp}</span><small>Potential {d.Potential} · {d.Prescriber_Status}</small></button>)}</div></aside><div className="panel"><h2>{doctor?.Doctor_Name||'Select a doctor'}</h2>{doctor?<><p>{doctor.Specialties} · {doctor.Hospital||'Hospital not supplied'}</p><p>{doctor.Area} · {doctor.Camp} · Potential {doctor.Potential}</p><p>Pharmacy: <strong>{pharmacyName(doctor.Pharmacy_ID)}</strong> · OP timing: {doctor.OP_Timing||'Not supplied'} · Call schedule: {doctor.Call_Schedule}</p><p>Last recorded prescription: <strong>{lastRx?date(lastRx.Prescription_Date)+' · '+days(lastRx.Prescription_Date,today)+' days ago':'No dated prescription logged'}</strong></p><button className="button" onClick={()=>open('DOCTOR_PRODUCTS')}>+ Link / discuss a product</button><h3>Products linked to this doctor</h3><DataTable columns={[{label:'Product',render:r=>productName(r.Product_SKU)},{label:'Relationship',key:'Relationship'},{label:'Notes',key:'Notes'},{label:'Action',render:r=><button className="text-button" onClick={()=>open('DOCTOR_PRODUCTS',r)}>Edit</button>}]} rows={data.DOCTOR_PRODUCTS.filter(r=>r.Doctor_ID===doctorId&&r.Active==='YES')} empty="No product links yet. Choose products from the existing app catalogue."/><h3>Latest pharmacy stock</h3><DataTable columns={[{label:'Product',render:r=>productName(r.Product_SKU)},{label:'Remaining',render:r=>exact(r.Remaining_Units)+' '+r.Quantity_Unit},{label:'Checked',render:r=>date(r.Checked_Date)}]} rows={stock}/><p className="scope-note">This pharmacy stock is shared by its linked doctors. A prescription does not automatically reduce it.</p></>:<p>Open a doctor to see pharmacy stock, product relationships and recorded prescription activity.</p>}</div></div>}
    {(section==='RX_ACTIVITY'||section==='doctors')&&<ChartPanel title="Logged prescription activity" subtitle="Product entries by actual prescription month · unknown dates excluded" unit="Entries" type="bar" labels={months.map(monthLabel)} datasets={[{label:'Logged product entries',data:chartRows.map(r=>r.count)}]} columns={[{label:'Month',render:r=>monthLabel(r.month)},{label:'Entries',key:'count'}]} rows={chartRows} takeaway={rx.filter(r=>!r.Prescription_Date).length+' entries have an unknown prescription date. Activity is not agency revenue or confirmed dispensing.'}/>}
    <section className="panel field-records"><div className="panel-header"><h2>{section==='doctors'?'Recorded prescriptions':sections.find(s=>s[0]===section)?.[1]}</h2>{section==='FOLLOW_UPS'&&<label><input type="checkbox" checked={showClosed} onChange={e=>setShowClosed(e.target.checked)}/> Include completed / cancelled</label>}{section==='PHARMACY_STOCK_CHECKS'&&<label>Recheck after days<input type="number" min="1" value={staleDays} onChange={e=>setStaleDays(Math.max(1,Number(e.target.value)||1))}/></label>}</div><DataTable columns={columns} rows={rows}/>{section==='TARGETS'&&<p className="scope-note">Secondary revenue includes all agency statement sales, including direct connections. Prescription targets use dated logged quantities; POB targets use booked quantities. These metrics are never added together.</p>}</section>
    {editor&&<div className="field-modal-backdrop"><section ref={editorElement} onKeyDown={e=>{if(e.key==='Escape'&&!saving&&window.confirm('Discard this entry?'))setEditor(null);if(e.key==='Tab'){const nodes=[...editorElement.current.querySelectorAll('button:not([disabled]),input:not([disabled]),select:not([disabled]),textarea:not([disabled])')];const first=nodes[0],last=nodes.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}}} className="field-editor panel" role="dialog" aria-modal="true" aria-labelledby="field-editor-title"><div className="panel-header"><h2 id="field-editor-title">{editor.operation==='update'?'Edit':'Log'} {names[editor.table]}</h2><button className="button" disabled={saving} onClick={()=>{if(window.confirm('Discard this entry?'))setEditor(null);}}>Close</button></div>{error&&<p className="message error" role="alert">{error}</p>}<form onSubmit={save}><div className="field-form-grid">{FIELD_SPEC[editor.table].headers.filter((h,i)=>{if(i===0||['Created_At','Updated_At'].includes(h))return false;if(editor.table==='TARGETS'){if(h==='Doctor_ID')return record.Scope==='DOCTOR';if(h==='Pharmacy_ID')return record.Scope==='PHARMACY';if(h==='Agency')return record.Scope==='AGENCY';if(['Product_SKU','Quantity_Unit'].includes(h))return record.Metric!=='SECONDARY_REVENUE';}if(editor.table==='FOLLOW_UPS'&&h==='Completed_Date')return record.Status==='DONE';return true;}).map(h=>{
      const spec=FIELD_SPEC[editor.table],required=spec.required.includes(h),choices=(h==='Scope'&&editor.table==='TARGETS'?(record.Metric==='SECONDARY_REVENUE'?['OVERALL','AGENCY']:record.Metric==='RX_UNITS'?['OVERALL','DOCTOR','PHARMACY']:spec.options.Scope):spec.options?.[h])||(h==='Quantity_Unit'?QUANTITY_UNITS:h==='Agency'?data.agencies:null),value=record[h]??'';
      const change=e=>{const v=e.target.value;setRecord(r=>{const next={...r,[h]:v};if(h==='Doctor_ID'&&v&&!r.Pharmacy_ID)next.Pharmacy_ID=data.DOCTORS.find(d=>d.Doctor_ID===v)?.Pharmacy_ID||'';if(h==='Status'&&editor.table==='FOLLOW_UPS')next.Completed_Date=v==='DONE'?today:'';if(h==='Metric'&&v==='SECONDARY_REVENUE'){next.Scope='OVERALL';next.Doctor_ID='';next.Pharmacy_ID='';next.Product_SKU='';next.Quantity_Unit='';}if(h==='Metric'&&v==='RX_UNITS'&&next.Scope==='AGENCY'){next.Scope='OVERALL';next.Agency='';}if(h==='Scope'&&editor.table==='TARGETS'){next.Doctor_ID='';next.Pharmacy_ID='';next.Agency='';}return next;});};
      const entities=h==='Doctor_ID'?data.DOCTORS.map(d=>[d.Doctor_ID,d.Doctor_Name+' · '+d.Camp]):h==='Pharmacy_ID'?data.PHARMACIES.map(p=>[p.Pharmacy_ID,p.Pharmacy_Name+' · '+p.Area+' · '+p.Camp]):h==='Product_SKU'?data.products.map(p=>[p.Product_SKU,p.Product_Name+' · '+p.Product_SKU+(p.Active?'':' · historical')]):null;
      return <label key={h} className={h==='Notes'?'field-wide':''}>{label(h)}{required?' *':''}{h==='Notes'?<textarea autoFocus={false} value={value} onChange={change} maxLength={2000}/>:entities||choices?<select required={required} value={value} onChange={change}><option value="">{required?'Choose…':'Not specified'}</option>{(entities||choices.map(c=>[c,label(c)])).map(([v,n])=><option key={v} value={v}>{n}</option>)}</select>:<input required={required} value={value} onChange={change} type={h==='Month'?'month':spec.dates?.includes(h)?'date':spec.numbers?.includes(h)?'number':'text'} min={spec.numbers?.includes(h)?0:undefined} step={spec.numbers?.includes(h)?'any':undefined} maxLength={2000} max={['Prescription_Date','Reported_Date','Checked_Date','Booking_Date','Fulfilled_Date','Completed_Date'].includes(h)?today:undefined}/>}</label>;
    })}</div><p className="scope-note">Keep unknown quantities and prescription dates blank. Record the pharmacist’s stock check separately. Patient details are not needed.</p><button className="button" disabled={saving} type="submit">{saving?'Saving to Google Sheets…':'Save to Google Sheets'}</button></form></section></div>}
    <p className="scope-note">This browser reuses saved field data after page reloads. Refresh data reads the sheet again; successful saves update the stored snapshot.</p>
  </section>;
}
