'use client';
import {useEffect,useRef,useState} from 'react';
import {DataTable,exact} from './ChartPanel.jsx';
import {FIELD_SPEC,QUANTITY_UNITS,indiaToday} from '../lib/field-tracking.js';
import DoctorDirectory from './DoctorDirectory.jsx';
import {createFieldSession} from '../lib/field-session.js';
const sections=[['doctors','Doctors'],['POB_ACTIVITY','POBs']];
const names={DOCTORS:'Doctor',DOCTOR_PRODUCTS:'Product link',POB_ACTIVITY:'POB'};
const titles={Doctor_ID:'Doctor',Pharmacy_ID:'Pharmacy',Product_SKU:'Product',Quantity_Unit:'Quantity unit',Active:'Active'};
const label=h=>titles[h]||h.replaceAll('_',' ');
const date=v=>v?new Date(v+'T12:00:00Z').toLocaleDateString('en-IN',{day:'2-digit',month:'short',year:'numeric',timeZone:'Asia/Kolkata'}):'Date unknown';
const days=(v,today)=>v?Math.floor((Date.parse(today+'T12:00:00Z')-Date.parse(v+'T12:00:00Z'))/86400000):null;
async function request(body){const response=await fetch('/api/fields',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body),cache:'no-store',signal:AbortSignal.timeout(60000)});let result;try{result=await response.json();}catch{throw new Error('The field-data connection returned an invalid response. Your entry is kept in the form.');}if(!response.ok)throw new Error(result.error||'Could not load field data.');return result;}
export default function FieldWorkspace({visible,refreshVersion,onLoadingChange}){
  const [data,setData]=useState(null),[loading,setLoading]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
  const [section,setSection]=useState('doctors'),[doctorId,setDoctorId]=useState(''),[directoryReset,setDirectoryReset]=useState(0);
  const [scope,setScope]=useState({product:'',pharmacy:'',start:'',end:''});
  const [links,setLinks]=useState([]),[productSearch,setProductSearch]=useState('');
  const [editor,setEditor]=useState(null),[record,setRecord]=useState({}),[saving,setSaving]=useState(false);
  const [session]=useState(()=>createFieldSession(force=>request({action:'read',force}).then(r=>r.data),()=>localStorage));
  const loadedVersion=useRef(-1),readEpoch=useRef(0),editorElement=useRef(null),editorOrigin=useRef(null),today=indiaToday();
  useEffect(()=>{if(!visible||loadedVersion.current===refreshVersion)return;loadedVersion.current=refreshVersion;const epoch=++readEpoch.current;setError('');if(refreshVersion===0){const cached=session.restore();if(cached){setData(cached);setLoading(false);return;}}setLoading(true);session.load(refreshVersion>0).then(value=>{if(epoch===readEpoch.current){setData(value);setNotice('');}}).catch(e=>{if(epoch===readEpoch.current)setError('Refresh failed; the previous saved data is still shown. '+e.message);}).finally(()=>{if(epoch===readEpoch.current)setLoading(false);});},[visible,refreshVersion,session]);
  useEffect(()=>{onLoadingChange?.(visible&&loading);},[visible,loading,onLoadingChange]);
  useEffect(()=>{if(editor)editorElement.current?.querySelector('input,select,textarea')?.focus();else editorOrigin.current?.focus();},[editor]);
  function open(table,existing){const spec=FIELD_SPEC[table],r=Object.fromEntries(spec.headers.map(h=>[h,existing?.[h]??'']));r[spec.headers[0]]=existing?.[spec.headers[0]]||crypto.randomUUID();
    if(!existing){if(table!=='DOCTORS'&&spec.headers.includes('Doctor_ID'))r.Doctor_ID=doctorId;if(spec.headers.includes('Pharmacy_ID'))r.Pharmacy_ID=scope.pharmacy||data.DOCTORS.find(d=>d.Doctor_ID===doctorId)?.Pharmacy_ID||'';if(spec.headers.includes('Product_SKU'))r.Product_SKU=scope.product;
      for(const h of ['Booking_Date'])if(spec.headers.includes(h))r[h]=today;
      if(table==='DOCTORS'){r.Pharmacy_ID='';r.Prescriber_Status='NRx';}if(table==='POB_ACTIVITY')r.Status='BOOKED';
      if(spec.headers.includes('Active'))r.Active='YES';if(table==='DOCTOR_PRODUCTS')r.Relationship='EXISTING';
    }if(r.Doctor_ID&&table!=='DOCTORS')r.Pharmacy_ID=data.DOCTORS.find(d=>d.Doctor_ID===r.Doctor_ID)?.Pharmacy_ID||'';setLinks(table==='DOCTOR_PRODUCTS'&&!existing&&r.Product_SKU?[{Link_ID:r.Link_ID,Product_SKU:r.Product_SKU}]:[]);setProductSearch('');editorOrigin.current=document.activeElement;setRecord(r);setEditor({table,operation:existing?'update':'create',previous:existing});setError('');setNotice('');}
  async function save(e){e.preventDefault();setSaving(true);setError('');try{const result=await request({action:'save',...editor,record:editor.table==='DOCTOR_PRODUCTS'&&editor.operation==='create'?{...record,Product_SKU:''}:record,...(editor.table==='DOCTOR_PRODUCTS'&&editor.operation==='create'?{links}: {})});if(editor.table==='DOCTOR_PRODUCTS'&&editor.operation==='create'&&!Array.isArray(result.records))throw new Error('Update the existing Apps Script deployment with the new Code.gs before saving multiple products.');setData(session.saved(editor.table,result.records||result.record));setNotice(names[editor.table]+' saved.');if(editor.table==='DOCTORS'){setDoctorId(result.record.Doctor_ID);setScope({product:'',pharmacy:'',start:'',end:''});setDirectoryReset(v=>v+1);}setEditor(null);}catch(e){setError(e.message);}finally{setSaving(false);}}
  if(!visible)return null;
  if(!data)return <section className="panel field-workspace"><h2>Doctor &amp; pharmacy workspace</h2><p role="status">{loading?'Loading doctors, pharmacies and your activity logs…':'Tracking data has not loaded.'}</p>{error&&<p className="message error" role="alert">{error}</p>}<button className="button" disabled={loading} onClick={()=>{loadedVersion.current=refreshVersion;const epoch=++readEpoch.current;setLoading(true);setError('');session.load(true).then(value=>{if(epoch===readEpoch.current)setData(value);}).catch(e=>{if(epoch===readEpoch.current)setError('Refresh failed; the previous saved data is still shown. '+e.message);}).finally(()=>{if(epoch===readEpoch.current)setLoading(false);});}}>Retry connection</button></section>;
  const doctor=data.DOCTORS.find(d=>d.Doctor_ID===doctorId);
  const doctorName=id=>data.DOCTORS.find(d=>d.Doctor_ID===id)?.Doctor_Name||id||'—';
  const pharmacyName=id=>data.PHARMACIES.find(p=>p.Pharmacy_ID===id)?.Pharmacy_Name||id||'—';
  const productName=sku=>data.products.find(p=>p.Product_SKU===sku)?.Product_Name||sku||'General';
  const matches=r=>(!doctorId||r.Doctor_ID===doctorId)&&(!scope.pharmacy||r.Pharmacy_ID===scope.pharmacy)&&(!scope.product||r.Product_SKU===scope.product);
  const inPeriod=(r,key)=>{const d=r[key];return (!scope.start||d&&d>=scope.start)&&(!scope.end||d&&d<=scope.end);};
  const activityTable=section==='doctors'?'POB_ACTIVITY':section;
  const rows=(data[activityTable]||[]).filter(r=>matches(r)&&inPeriod(r,'Booking_Date'));
  const lastPOB=data.POB_ACTIVITY.filter(r=>r.Doctor_ID===doctorId&&r.Booking_Date&&(!scope.product||r.Product_SKU===scope.product)).sort((a,b)=>b.Booking_Date.localeCompare(a.Booking_Date))[0];
  const columns=[{label:'Doctor',render:r=>doctorName(r.Doctor_ID)},{label:'Pharmacy',render:r=>pharmacyName(r.Pharmacy_ID)},{label:'Product',render:r=>productName(r.Product_SKU)}];
  if(activityTable==='POB_ACTIVITY')columns.push({label:'Booked',render:r=>date(r.Booking_Date)},{label:'Booked units',render:r=>exact(r.Booked_Units)+' '+r.Quantity_Unit},{label:'Supplied units',render:r=>r.Fulfilled_Units===''?'Unknown':exact(r.Fulfilled_Units)+' '+r.Quantity_Unit},{label:'Status',key:'Status'});
  columns.push({label:'Notes',key:'Notes'},{label:'Action',render:r=><button className="text-button" onClick={()=>open(activityTable,r)}>Edit</button>});
  return <section className="field-workspace" aria-busy={loading}>
    <div className="product-report-tabs" aria-label="Tracking sections">{sections.map(([key,title])=><button type="button" key={key} className={section===key?"field-tab-selected":""} aria-pressed={section===key} onClick={()=>setSection(key)}>{title}</button>)}</div>
    {error&&<p className="message error" role="alert">{error}</p>}{notice&&<p className="message" role="status">{notice}</p>}
    <div className="field-scope panel"><label>Doctor<select value={doctorId} onChange={e=>{setDoctorId(e.target.value);setScope(s=>({...s,pharmacy:''}));}}><option value="">All doctors</option>{data.DOCTORS.map(d=><option key={d.Doctor_ID} value={d.Doctor_ID}>{d.Doctor_Name} · {d.Camp}</option>)}</select></label><label>Pharmacy<select disabled={!!doctor} value={doctor?.Pharmacy_ID||scope.pharmacy} onChange={e=>setScope(s=>({...s,pharmacy:e.target.value}))}><option value="">{doctor?'Linked pharmacy':'All pharmacies'}</option>{data.PHARMACIES.map(p=><option key={p.Pharmacy_ID} value={p.Pharmacy_ID}>{p.Pharmacy_Name} · {p.Area} · {p.Camp}</option>)}</select></label><label>Product<select value={scope.product} onChange={e=>setScope(s=>({...s,product:e.target.value}))}><option value="">All products</option>{data.products.map(p=><option key={p.Product_SKU} value={p.Product_SKU}>{p.Product_Name} · {p.Product_SKU}{p.Active?'':' · excluded / historical'}</option>)}</select></label><label>From<input type="date" value={scope.start} onChange={e=>setScope(s=>({...s,start:e.target.value}))}/></label><label>To<input type="date" value={scope.end} min={scope.start||undefined} onChange={e=>setScope(s=>({...s,end:e.target.value}))}/></label><button className="text-button" onClick={()=>{setDoctorId('');setScope({product:'',pharmacy:'',start:'',end:''});}}>Reset</button></div>
    <div className="field-actions">{[['POB_ACTIVITY','+ POB']].map(([table,title])=><button key={table} className="button" onClick={()=>open(table)}>{title}</button>)}</div>
    <section className="kpi-grid field-kpis"><article className="kpi"><p>POB product entries</p><strong>{data.POB_ACTIVITY.filter(matches).length}</strong><small>Recorded orders</small></article></section>
    {section==='doctors'&&<div className="field-doctor-grid"><DoctorDirectory data={data} doctorId={doctorId} onSelect={id=>{setDoctorId(id);setScope(s=>({...s,pharmacy:''}));}} onAdd={()=>open('DOCTORS')} resetVersion={directoryReset}/><div className="panel"><h2>{doctor?.Doctor_Name||'Select a doctor'}</h2>{doctor?<><p>{doctor.Specialties} · {doctor.Hospital||'Hospital not supplied'}</p><p>{doctor.Area} · {doctor.Camp} · Potential {doctor.Potential}</p><p>Pharmacy: <strong>{pharmacyName(doctor.Pharmacy_ID)}</strong> · OP timing: {doctor.OP_Timing||'Not supplied'} · Call schedule: {doctor.Call_Schedule}</p><p>Last recorded POB: <strong>{lastPOB?date(lastPOB.Booking_Date)+' · '+days(lastPOB.Booking_Date,today)+' days ago':'No POB logged'}</strong></p><button className="button" onClick={()=>open('DOCTORS',doctor)}>Edit doctor</button><button className="button" onClick={()=>open('DOCTOR_PRODUCTS')}>+ Link / discuss products</button><h3>Products linked to this doctor</h3><DataTable columns={[{label:'Product',render:r=>productName(r.Product_SKU)},{label:'Relationship',key:'Relationship'},{label:'Notes',key:'Notes'},{label:'Action',render:r=><button className="text-button" onClick={()=>open('DOCTOR_PRODUCTS',r)}>Edit</button>}]} rows={data.DOCTOR_PRODUCTS.filter(r=>r.Doctor_ID===doctorId&&r.Active==='YES')} empty="No product links yet. Choose products from the existing app catalogue."/></>:<p>Open a doctor to see the linked pharmacy, product relationships and POBs.</p>}</div></div>}
    <section className="panel field-records"><div className="panel-header"><h2>{section==='doctors'?'Recorded POBs':sections.find(s=>s[0]===section)?.[1]}</h2></div><DataTable columns={columns} rows={rows}/></section>
    {editor&&<div className="field-modal-backdrop"><section ref={editorElement} onKeyDown={e=>{if(e.key==='Escape'&&!saving&&window.confirm('Discard this entry?'))setEditor(null);if(e.key==='Tab'){const nodes=[...editorElement.current.querySelectorAll('button:not([disabled]),input:not([disabled]),select:not([disabled]),textarea:not([disabled])')];const first=nodes[0],last=nodes.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}}} className="field-editor panel" role="dialog" aria-modal="true" aria-labelledby="field-editor-title"><div className="panel-header"><h2 id="field-editor-title">{editor.operation==='update'?'Edit':editor.table==='DOCTORS'?'Add':'Log'} {editor.table==='DOCTOR_PRODUCTS'&&editor.operation==='create'?'Product links':names[editor.table]}</h2><button className="button" disabled={saving} onClick={()=>{if(window.confirm('Discard this entry?'))setEditor(null);}}>Close</button></div>{error&&<p className="message error" role="alert">{error}</p>}<form onSubmit={save}><div className="field-form-grid">{FIELD_SPEC[editor.table].headers.filter((h,i)=>{if(i===0||['Created_At','Updated_At'].includes(h))return false;return true;}).map(h=>{
      const spec=FIELD_SPEC[editor.table],required=spec.required.includes(h),choices=spec.options?.[h]||(h==='Quantity_Unit'?QUANTITY_UNITS:h==='Agency'?data.agencies:null),value=record[h]??'';
      if(h==='Pharmacy_ID'&&record.Doctor_ID&&(editor.table!=='DOCTORS'||editor.operation==='update'))return <label key={h}>Linked pharmacy<input readOnly value={data.PHARMACIES.find(p=>p.Pharmacy_ID===(editor.table==='DOCTORS'?editor.previous.Pharmacy_ID:data.DOCTORS.find(d=>d.Doctor_ID===record.Doctor_ID)?.Pharmacy_ID))?.Pharmacy_Name||'No linked pharmacy in doctor master'}/><small>Fixed for this doctor.</small></label>;
      const change=e=>{const v=e.target.value;setRecord(r=>{const next={...r,[h]:v};if(h==='Doctor_ID')next.Pharmacy_ID=data.DOCTORS.find(d=>d.Doctor_ID===v)?.Pharmacy_ID||'';return next;});};
      if(h==='Product_SKU'&&editor.table==='DOCTOR_PRODUCTS'&&editor.operation==='create')return <fieldset key={h} className="field-wide product-picker"><legend>Products * · {links.length} selected</legend><input type="search" aria-label="Find products to link" placeholder="Find a product" value={productSearch} onChange={e=>setProductSearch(e.target.value)}/><div className="product-picker-list">{data.products.filter(p=>(p.Product_Name+' '+p.Product_SKU).toLowerCase().includes(productSearch.toLowerCase())).map(p=><label key={p.Product_SKU}><input type="checkbox" checked={links.some(l=>l.Product_SKU===p.Product_SKU)} onChange={e=>setLinks(current=>e.target.checked?[...current,{Link_ID:crypto.randomUUID(),Product_SKU:p.Product_SKU}]:current.filter(l=>l.Product_SKU!==p.Product_SKU))}/><span>{p.Product_Name}<small>{p.Product_SKU}</small></span></label>)}</div><small>The relationship, pharmacy, dates and notes apply to each selected product.</small></fieldset>;
      const entities=h==='Doctor_ID'?data.DOCTORS.map(d=>[d.Doctor_ID,d.Doctor_Name+' · '+d.Camp]):h==='Pharmacy_ID'?data.PHARMACIES.map(p=>[p.Pharmacy_ID,p.Pharmacy_Name+' · '+p.Area+' · '+p.Camp]):h==='Product_SKU'?data.products.map(p=>[p.Product_SKU,p.Product_Name+' · '+p.Product_SKU+(p.Active?'':' · historical')]):null;
      if(editor.table==='DOCTORS'&&['Area','Camp','Specialties','Stockist','OP_Timing','Call_Schedule'].includes(h))return <label key={h}>{label(h)}{required?' *':''}<input list={'doctor-options-'+h} required={required} value={value} onChange={change} maxLength={2000}/><datalist id={'doctor-options-'+h}>{[...new Set(data.DOCTORS.flatMap(d=>h==='Specialties'?String(d[h]||'').split(/[;,|]/).map(v=>v.trim()):[d[h]]).filter(Boolean))].sort().map(v=><option key={v} value={v}/>)}</datalist>{h==='Specialties'&&<small>Separate multiple specialties with commas.</small>}</label>;
      return <label key={h} className={h==='Notes'?'field-wide':''}>{label(h)}{required?' *':''}{h==='Notes'?<textarea autoFocus={false} value={value} onChange={change} maxLength={2000}/>:entities||choices?<select required={required} value={value} onChange={change}><option value="">{required?'Choose…':'Not specified'}</option>{(entities||choices.map(c=>[c,label(c)])).map(([v,n])=><option key={v} value={v}>{n}</option>)}</select>:<input required={required} value={value} onChange={change} type={spec.dates?.includes(h)?'date':spec.numbers?.includes(h)?'number':'text'} min={spec.numbers?.includes(h)?0:undefined} step={spec.numbers?.includes(h)?'any':undefined} maxLength={2000} max={['Booking_Date','Fulfilled_Date'].includes(h)?today:undefined}/>}</label>;
    })}</div><p className="scope-note">Use consistent quantity units. Patient details are not needed.</p><button className="button" disabled={saving||(editor.table==='DOCTOR_PRODUCTS'&&editor.operation==='create'&&!links.length)} type="submit">{saving?'Saving…':'Save'}</button></form></section></div>}
    {loading&&<p className="message" role="status">Refreshing doctor and pharmacy data from the sheet…</p>}
    <p className="scope-note">This browser reuses saved field data after page reloads. Refresh data reads the sheet again; successful saves update the stored snapshot.</p>
  </section>;
}
