'use client';
import {useState} from 'react';
import ChartPanel,{exact,monthLabel} from './ChartPanel.jsx';
import {productExplorerModel,productStatuses} from '../lib/product-explorer.js';

export default function ProductCatalog({data,onSelect,onAgency,showInsights=true}) {
  const [search,setSearch]=useState(''),[status,setStatus]=useState('all');
  const f=data.filters,period=f.start===f.end?monthLabel(f.end):monthLabel(f.start)+' – '+monthLabel(f.end);
  const model=productExplorerModel(data.productAnalysis,data.options.products,{search,status,agencies:f.agency?[f.agency]:data.options.agencies});
  const selectedStatus=productStatuses.find(item=>item.key===status)?.label;
  return <section className="product-explorer" aria-label="Product explorer visuals">
    <div className="explorer-toolbar"><label>Find a product<input type="search" placeholder="Search name, SKU or brand" value={search} onChange={e=>setSearch(e.target.value)}/></label><label>Movement status<select value={status} onChange={e=>setStatus(e.target.value)}><option value="all">All products</option>{productStatuses.map(item=><option key={item.key} value={item.key}>{item.label}</option>)}</select></label><button className="text-button" onClick={()=>{setSearch('');setStatus('all');}}>Reset explorer</button></div>
    <div className="chart-grid explorer-visuals">
      <ChartPanel title="Product movement mix" subtitle={period+' · product counts · closing stock at '+monthLabel(f.end)} horizontal type="bar" unit="Products" chartHeight={250} labels={model.categories.map(row=>row.label)} datasets={[{label:'Products',data:model.categories.map(row=>row.count)}]} onPoint={index=>setStatus(model.categories[index].key)} interactionHint="Select a status to filter the product list and agency chart below." columns={[{label:'Status',render:row=><button onClick={()=>setStatus(row.key)}>{row.label}</button>},{label:'Products',numeric:true,key:'count'}]} rows={model.categories} takeaway={showInsights?[model.products.length+' matching products: '+model.categories.find(row=>row.key==='selling').count+' selling with stock, '+model.categories.find(row=>row.key==='idle').count+' with zero sales and remaining stock.',...(model.unknown?[model.unknown+' products have incomplete observations or adjustments. They are not labelled as zero-sale.']:[])]:null}/>
      <ChartPanel title="Agency sales & remaining stock" subtitle={'Sales: '+period+' · stock: '+monthLabel(f.end)+(selectedStatus?' · '+selectedStatus:'')} horizontal type="bar" unit="Units" chartHeight={250} labels={model.balance.map(row=>row.agency)} datasets={[{label:'Units sold in period',data:model.balance.map(row=>row.units),color:'#3489e0'},{label:'Closing stock units',data:model.balance.map(row=>row.qoh),color:'#e65722'}]} onPoint={index=>onAgency(model.balance[index].agency)} interactionHint="Select an agency to focus the explorer. Sales are a period flow; stock is the end-month snapshot." columns={[{label:'Agency',render:row=><button onClick={()=>onAgency(row.agency)}>{row.agency}</button>},{label:'Period units sold',numeric:true,render:row=>exact(row.units)},{label:'Closing units',numeric:true,render:row=>exact(row.qoh)},{label:'Included product/agency pairs',numeric:true,key:'included'},{label:'Excluded observed pairs',numeric:true,key:'excluded'}]} rows={model.balance} takeaway={showInsights?model.balance.map(row=>row.included?row.agency+': '+exact(row.units)+' period sale units and '+exact(row.qoh)+' closing units across '+row.included+' comparable product/agency pairs'+(row.excluded?'; '+row.excluded+' observed pairs excluded.':'.'):row.agency+': no comparable product/agency observations for this selection.'):null}/>
    </div>
    <p className="scope-note">The movement mix covers matching catalogue products. Agency bars use only products with complete sales and closing observations; unavailable values stay —. All visuals follow the persistent report filters.</p>
    <section className="panel product-catalog" aria-label="Explore products"><div className="catalog-heading"><div><h2>{selectedStatus||'Choose a product'}</h2><p>Open its sales trend, stock trend, restocking and agency comparisons.</p></div><span className="count">{model.visible.length} products</span></div><div className="product-list">{model.visible.map(p=><button type="button" className="product-card" key={p.key} onClick={()=>onSelect(p.key)}><span><strong>{p.name}</strong><small>{[p.brand,p.sku].filter(Boolean).join(' · ')}</small><span className="catalog-metrics"><span>Sold <b>{exact(p.units)}</b></span><span>Stock <b>{exact(p.qoh)}</b></span></span></span><span aria-hidden="true">↗</span></button>)}</div>{!model.visible.length&&<p className="empty-text">No products match this search and movement status.</p>}</section>
  </section>;
}
